version: '3.7'

services:
  vertica:
    image: "123456789012.dkr.ecr.eu-central-1.amazonaws.com/vertica:10.0.1-5.CentOS_8.3.2011"
    ports:
      - "5433:5433"
    volumes:
      - vertica-data:/data
      - ./.docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      VMART_LOAD_DATA: "${VMART_LOAD_DATA:-n}"
      APP_DB_USER: "app_user"
      APP_DB_PASSWORD: "${VERTICA_APP_DB_USER:-password123}"
      TZ: "${VERTICA_CUSTOM_TZ:-Europe/Prague}"
      # Set "y", if you want to debug failing startup
      DEBUG_FAILING_STARTUP: "n"

volumes:
  vertica-data:
